### ISSUE TITLE
Why donot  OCR predict net load any pretrained value？

### ISSUE THREAD

**Issue by yuetz** [tyxsspa/AnyText#52]
The func `create_predictor(model_dir=None, model_lang='ch', is_onnx=False)` in `cldm/recognizer.py` has a param model_dir.
But `self.text_predictor = create_predictor().eval()` in ControlNet donot pass any params into this func.
Why? Is it that the glyph embedding is not useful when inference?

**Comment by tyxsspa** [comment]
Hi !
Sure the glyph embedding is used in both inference and training.
The weights of the OCR model have already been integrated into the AnyText ckpt, so just initializing the network structure is enough, no need to provide model_dir here. However, when debugging the OCR module during the development process(for example, checking its recognition results, testing the value of text perceptual loss, etc.), you can simply load the weights of a small OCR model instead of the whole ckpt, and the model_dir here only serves this purpose, see the main() function of recognizer.py.

**Comment by yuetz** [comment]
Thanks a lot！

**Comment by tydia** [comment]
@tyxsspa Which of the OCR checkpoint are you using? Is it the ch_ptocr_v3_rec_infer.pth from [PaddleOCR2Pytorch](https://github.com/frotms/PaddleOCR2Pytorch)?
